name: "GeoMop"
description: "Geosphere model preparation"
author :
  name : Jan Brezina
  email : jan.brezina@tul.cz

url: "http://localhost:4000"
sass:
  sass_dir: assets/sass
  style:    expanded
    
exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'config.rb']
paginate: 4
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
highlighter: rouge
